name: Deploy 

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-v2:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Vérification que les variables sont bien définies
            echo "DOCKER_USERNAME: $DOCKER_USERNAME"
            echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
            
            # Login à Docker sans interaction utilisateur
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            # Pull de l'image la plus récente
            docker pull "$DOCKER_USERNAME/portfolio-v2:latest"
            
            # Arrêt et suppression du conteneur existant si présent
            docker stop portfolio || true
            docker rm portfolio || true
            
            # Lancer le conteneur avec un tag spécifique
            docker run -d --name portfolio -p 8080:80 "$DOCKER_USERNAME/portfolio-v2:latest"

